/// Base interface for all Dascade UI elements.
library;

import 'package:dascade/src/ui/gfx/painter.dart';
import 'package:dascade/src/ui/math/rect.dart';
import 'package:dascade/src/ui/runtime.dart';

/// Base interface for all Dascade UI elements.
///
/// A [DUElement] represents a concrete, stateful region of the UI
/// with a stable identity and a fixed layout rectangle for the
/// current frame.
///
/// Elements participate in two distinct phases each frame:
/// - [interact]: input handling and state updates
/// - [render]: visual output
///
/// This separation keeps input logic deterministic and makes
/// rendering purely a function of state.
abstract interface class DUElement {
  
  /// Stable identifier for this element.
  ///
  /// IDs are generated by the layout system and must remain
  /// consistent across frames as long as the UI structure
  /// does not change.
  int get id;

  /// Layout rectangle occupied by this element for the current frame.
  DURect get rect;

  /// Handles user interaction and updates element state.
  ///
  /// Called once per frame before rendering.
  /// Implementations may read input state, mutate stored state,
  /// and request focus or capture.
  void interact(DUIRuntime r) {}

  /// Renders the element using the provided painter.
  ///
  /// Rendering must not mutate shared UI state.
  void render(DUIPainter p, DUIRuntime r);

}
